apiVersion: v1
kind: ConfigMap
metadata:
  namespace: x5-lot14
  name: app-variables14
data:
  SECRET_KEY: django-insecure-_pt+2ge#fs1@*klyk85(wx22@w7l!h$v8gur^vtvy%m9%dwle#
  ALLOWED_HOSTS: "*"
  VITE_API_URL: https://lot14.artw.dev/api/
  ## Параметры БД для lot14
  ENGINE: django.db.backends.postgresql
  DATABASE_URL: postgres-service
  DB_ENGINE: django.db.backends.postgresql
  DATABASE_NAME: lot14
  DATABASE_PORT: "5432"
  DB_HOST: postgres-service
  DB_NAME: lot14
  DB_PORT: "5432"
  #env variables for the postgres component
  POSTGRES_DB: lot14

  # #env variables for the backend component
  DJANGO_ENV: development
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_ADMIN_USER: admin
  DJANGO_ADMIN_EMAIL: "admin@example.com"
  DATABASE: postgres
  CORS_ORIGINS: '["https://lot14.artw.dev", "http://localhost:8065"]'
  CORS_ALLOW_ALL_ORIGINS: "1"


